### ISSUE TITLE
推荐

### ISSUE THREAD

**Issue by gaowanlu** [goodXHD/goodXHD.github.io#1]
# 三院科协有几个人专门搞CV和深度学习的，他们写过写笔记和博客、可以去看看。搞的比较好。
# https://github.com/neet-cv/ml.akasaki.space

**Comment by goodXHD** [comment]
哈哈，好的，谢谢万禄哥的提携，向万禄哥学习！！！

**Comment by gaowanlu** [comment]
### 不至于不至于，我只是看见了，瞅了两眼，你爱学这种，给你说一下。 ![沙雕表情 (2)](https://user-images.githubusercontent.com/57703023/147281231-ae4a611e-c67a-4977-9eaa-f23a03438953.gif)

**Comment by goodXHD** [comment]
哈哈，万禄哥考虑考研吗？还是去找实习？

**Comment by gaowanlu** [comment]
得考，学习就这几年，不急，打工得一辈子，趁年轻多往上爬一爬多学点，也没有人等着自己赶紧挣钱是吧，实习的话过年去投投试试，看看啥样。你好好学习，软工的课还是蛮有用的，也挺实用。

**Comment by goodXHD** [comment]
哈哈，行，跟着万禄哥的步伐前进
